### ISSUE TITLE
Cannot connect to vault, reporting "tls: unsupported SSLv2 handshake received"

### ISSUE THREAD

**Issue by p14n** [janstenpickle/scala-vault#6]
Hi,

We're trying to use VaultConfig to connect to a vault server running on docker.  Vault is reporting "tls: unsupported SSLv2 handshake received" - this suggests netty 3.1.0 is trying sslv2hello.  Has anyone seen this before?

There is another possibility and that is that the root ca cert is not available.  Other java clients report this however, so there is a difference.

Cheers

**Comment by janstenpickle** [comment]
It's likely that it's because of the self signed certificate, from what I understand about dispatch you should add your CA chain to the Java trusted keystore.

**Comment by p14n** [comment]
Thanks Chris
